version: "3.7"
services:
   shell:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "CO_API_KEY=wm3i2MGqTjkfOivAqCptxCb6BUrefj71IAeSBbUl"
    volumes:
      - ../:/opt/bron-llm
    networks:
      - bron-llm
    restart: always
networks:
  bron-llm:
